name = "min-academic"
license = "MIT"
licenselink = "https://github.com/zhixiao-zhang/hugo-min-academic/blob/master/LICENSE.md"
description = "A minimal Hugo theme for academic websites"
homepage = "https://forceoflife.github.io/"
demosite = "https://forceoflife.github.io/"
tags = ["minimal", "academic", "cv", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Zhixiao Zhang"
  homepage = "https://forceoflife.github.io/"
